# Generated by Django 2.1.3 on 2019-01-09 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webshop', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hiscore',
            options={'ordering': ('-score',)},
        ),
        migrations.AddField(
            model_name='hiscore',
            name='date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='sale',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
