# Generated by Django 2.1.3 on 2019-01-30 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webshop', '0008_sale_ref'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genre',
            name='games',
        ),
        migrations.AddField(
            model_name='game',
            name='genres',
            field=models.ManyToManyField(related_name='games', to='webshop.Genre'),
        ),
    ]
