# Generated by Django 2.1.3 on 2019-01-30 11:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webshop', '0009_auto_20190130_0749'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='developer',
            name='slug',
            field=models.SlugField(help_text='Developer name in webshop URLs', unique=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='genres',
            field=models.ManyToManyField(help_text='One to three genres may be chosen', related_name='games', to='webshop.Genre'),
        ),
        migrations.AlterField(
            model_name='game',
            name='price',
            field=models.DecimalField(decimal_places=2, default='0.00', max_digits=5),
        ),
        migrations.AlterField(
            model_name='game',
            name='slug',
            field=models.SlugField(help_text='Game name in webshop URLs', unique=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='url',
            field=models.URLField(help_text='Address where the game may be played, used in iframe.'),
        ),
        migrations.AlterField(
            model_name='game',
            name='users',
            field=models.ManyToManyField(blank=True, help_text='Who have purchased this game', related_name='games', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='genre',
            name='slug',
            field=models.SlugField(help_text='Genre name in webshop URLs', unique=True),
        ),
    ]
