# Generated by Django 2.1.3 on 2019-01-31 07:43

from django.db import migrations, models
import webshop.models


class Migration(migrations.Migration):

    dependencies = [
        ('webshop', '0010_auto_20190130_1321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='image',
            field=models.FileField(blank=True, help_text='Square-shaped image/icon for the game.', upload_to=webshop.models.Game.image_path),
        ),
    ]
