# Generated by Django 2.1.3 on 2019-02-05 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webshop', '0012_auto_20190204_0949'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='developer',
            options={'ordering': ('name',), 'permissions': (('admin', 'Full access to all games'),)},
        ),
    ]
