# Generated by Django 2.1.3 on 2019-02-12 12:58

from django.db import migrations
import webshop.slugs


class Migration(migrations.Migration):

    dependencies = [
        ('webshop', '0013_auto_20190205_1435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='slug',
            field=webshop.slugs.USlugField(help_text='Game name in webshop URLs'),
        ),
        migrations.AlterUniqueTogether(
            name='game',
            unique_together={('slug', 'developer')},
        ),
    ]
