# Generated by Django 2.1.3 on 2019-02-13 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webshop', '0017_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
